server:
  port: 9204

service-url:
  user-service: http://localhost:8201

spring:
  redis:
    host: localhost
#    password: 123456
    port: 6379

  cloud:
    gateway:
      routes:
        - id: requestratelimiter_route
          uri: ${service-url.user-service}
          predicates:
            - Method=GET
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1 #每秒允许处理的请求数量
                redis-rate-limiter.burstCapacity: 2 #每秒最大处理的请求数量
                key-resolver: "#{@ipKeyResolver}" #限流策略，对应策略的Bean

logging:
  level:
    org.springframework.cloud.gateway: debug

