server:
  port: 8801

spring:
  application:
    name: zuul-proxy

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka/

zuul:
  routes: #给服务配置路由
    user-service:
      path: /userService/**
    feign-service:
      path: /feignService/**
#  ignored-services: user-service,feign-service #关闭默认路由配置
#  prefix: /proxy #给网关路由添加前缀
#  sensitive-headers: Cookie,Set-Cookie,Authorization #配置过滤敏感的请求头信息，设置为空就不会过滤
  sensitive-headers:
  add-host-header: true #设置为true重定向是会添加host请求头
#  retryable: true # 关闭重试机制

#禁用过滤器
#  PreLogFilter:   #过滤器类名
#    pre:
#      disable: true #控制是否启用过滤器


#通过Actuator来查看Zuul中的路由信息
#通过访问 http://localhost:8801/actuator/routes 查看简单路由信息
#通过访问 http://localhost:8801/actuator/routes/details 查看详细路由信息
management:
  endpoints:
    web:
      exposure:
        include: 'routes'   #开启查看路由的端点


##Zuul自动集成了Ribbon和Hystrix
#hystrix:
#  command: #用于控制HystrixCommand的行为
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 1000 #配置HystrixCommand执行的超时时间，执行超过该时间会进行服务降级处理
#
##可以使用Ribbon的配置来设置路由转发时请求连接及处理的超时时间
#ribbon: #全局配置
#  ConnectTimeout: 1000 #服务请求连接超时时间（毫秒）
#  ReadTimeout: 3000 #服务请求处理超时时间（毫秒）

